apiVersion: v1
kind: Secret
metadata:
  name: petswipe-backend-secrets
type: Opaque
stringData:
  DB_PASS: replace-me
  JWT_SECRET: replace-with-a-long-random-secret
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me

