apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: petswipe
  labels:
    app.kubernetes.io/name: datadog
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: petswipe-platform
type: Opaque
stringData:
  api-key: REPLACE_WITH_DATADOG_API_KEY
  cluster-agent-token: REPLACE_WITH_CLUSTER_AGENT_TOKEN
