apiVersion: v1
kind: Service
metadata:
  name: datadog-agent
  labels:
    app.kubernetes.io/name: datadog-agent
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: petswipe-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: datadog-agent
  ports:
    - name: traceport
      port: 8126
      targetPort: traceport
      protocol: TCP
    - name: dogstatsd
      port: 8125
      targetPort: dogstatsd
      protocol: UDP
