apiVersion: v1
kind: ConfigMap
metadata:
  name: petswipe-frontend-config
data:
  NODE_ENV: production
  PORT: "3000"
  NEXT_TELEMETRY_DISABLED: "1"
  NEXT_PUBLIC_API_URL: https://api.petswipe.example.com/api

