apiVersion: v1
kind: ServiceAccount
metadata:
  name: petswipe-backend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: petswipe-frontend
automountServiceAccountToken: false

