name: AWS Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS
    runs-on: ubuntu-latest
    # pass through the region/password/invalidation ID
    env:
      AWS_REGION:      ${{ secrets.AWS_REGION }}
      DB_PASSWORD:     ${{ secrets.DB_PASSWORD }}
      CF_DISTRIBUTION_ID: ${{ secrets.CF_DISTRIBUTION_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Set up Node.js (for frontend build)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install frontend dependencies
        run: npm ci --prefix frontend

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Run AWS deployment script
        run: |
          chmod +x aws/deploy.sh
          bash aws/deploy.sh
